version: '3'

services:

  serverless-api:
    build: .
    environment:
      - DATABASE_HOST=postgres-serverless-api
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-serverless-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=serverless_api
      - POSTGRES_USER=sapi
      - POSTGRES_PASSWORD=sapi